### PR TITLE
add db.collection_names(); improve $in query

### PR DESCRIPTION
**Pull request by davidlatwe**
implement `collection_names()` for #37

### CODE REVIEW

**Comment by davidlatwe** [comment]
Should fix for #42 .
`$in` query now should get the result as same as MongoDB.

sorry about the commit title typo...

**Comment by davidlatwe** [comment]
Hi, is there anyone could help on this ?
Thanks :)

**Comment by davidlatwe** [comment]
Thanks ! @schapman1974

**Comment by lockefox** [comment]
Tyvm!

**Pull request merged**
