### PR TITLE
Separate prod/test requirements with setup.py

### PR DESCRIPTION
**Pull request by lockefox**
Had issues including `tinymongo` in projects because of `pytest` prod requirement.  Split prod/test requirements using `setup.py`.

* Removes `requirements.txt`
    * `pip install -e .` to install for dev
* Fixed `.travis.yml` to match new test method
    * `python setup.py test` to run testpass
    * `pip install pytest -U` added b/c of python3.3 build on travis only using pytest==2.9.2
* Added new notes to README to reflect change

**Prod Requirements**
    * `tinymongo>=3.2.1` (currently 3.5.0)
    * `tinydb-serialization>=1.0.4` (currently 1.0.4)

**Test Requirements**
    * `pytest>=3.2.0` (currently 3.2.2)
    * `py>=1.4.33` (currently 1.4.34)

### CODE REVIEW

**Comment by lockefox** [comment]
Please push version update to pypi?  This fix is needed to clean up some requirements bugs

**Comment by lockefox** [comment]
Please release to pypi?  There is still a dependency issue

**Comment by schapman1974** [comment]
Okay, released to pypi 0.2.0

**Comment by lockefox** [comment]
tyvm!

**Pull request merged**
